In [6]:
import numpy as np
import tensorflow as tf

from numpy.testing import (
    assert_, assert_equal, assert_raises, assert_raises_regex,
    assert_array_equal, assert_almost_equal, assert_array_almost_equal,
    HAS_REFCOUNT
    )

# Rank 1 array 

In [3]:
a = np.zeros((2,3))

In [4]:
print(a.shape)

(2, 3)


In [5]:
a = np.eye(3)[0]
print(a.shape)

(3,)


In [6]:
b = np.array([1,2])
print(b.shape)

(2,)


In [7]:
b = np.expand_dims(b,axis=1)
print(b.shape)

(2, 1)


In [8]:
b = np.expand_dims(b,axis=1)
print(b.shape)

(2, 1, 1)


# Synchronous Shuffling 

In [10]:
X = np.random.randn(5,4,3)
Y = np.random.randn(5,4)
print(X)
print(Y)
permutation = np.random.permutation(X.shape[0])
print("permutation ")
print(permutation)
X_shuffled = X[permutation,:,:]
Y_shuffled = Y[permutation,:]
print(X_shuffled)
print(Y_shuffled)

[[[-0.31276838  0.8455825   0.49019278]
  [-0.15697893  0.74686735 -0.17815361]
  [-0.49393696 -2.34541452 -0.26865282]
  [ 0.16633489  0.88581099 -0.07289856]]

 [[ 0.95583061  0.26822161 -0.0444783 ]
  [-0.03275515  1.57983117 -0.63221916]
  [-0.62470927  0.43818327  0.41314011]
  [-0.59016566 -1.34338561  0.15356295]]

 [[-0.48129321 -1.36282709 -0.13857507]
  [-0.02666569  0.93996542  1.40207892]
  [ 0.80864324  0.16157803  0.98590735]
  [-2.35996691  0.64249089 -2.14757953]]

 [[ 0.45123137  0.03459274 -1.5015139 ]
  [-0.63781811  0.40164509  1.5122646 ]
  [ 0.75480382 -0.26732757 -1.20334287]
  [-1.41422027 -1.39928794  0.38364972]]

 [[ 0.37186964 -0.08959438  0.31699282]
  [ 0.88383665 -1.04647055  1.31899976]
  [-0.35803898 -2.25454149 -1.35778043]
  [-0.31342359  1.0442274   0.71803855]]]
[[-1.49902866  1.96243033 -0.95895204 -0.28968606]
 [ 0.17566112  0.39378072 -0.08487153  0.73542515]
 [-0.47870454  0.37056908  0.24730688 -0.12784765]
 [ 1.37399329  0.32201985  0.52063797

### np.clip()

In [42]:
np.random.seed(3)
a = np.random.randn(1,3)
b = np.random.randn(2,3)
for c in [a, b]:
    print(c)
    np.clip(c, -1, 1, out=c)
    print(c)
    print()
print(a)
print(b)
print(c)

[[1.78862847 0.43650985 0.09649747]]
[[1.         0.43650985 0.09649747]]

[[-1.8634927  -0.2773882  -0.35475898]
 [-0.08274148 -0.62700068 -0.04381817]]
[[-1.         -0.2773882  -0.35475898]
 [-0.08274148 -0.62700068 -0.04381817]]

[[1.         0.43650985 0.09649747]]
[[-1.         -0.2773882  -0.35475898]
 [-0.08274148 -0.62700068 -0.04381817]]
[[-1.         -0.2773882  -0.35475898]
 [-0.08274148 -0.62700068 -0.04381817]]


In [45]:
arr = [-1, 5, 2, 3, 10, -4, -9]
out = np.clip(arr, 2, 7)
tgt = [2, 5, 2, 3, 7, 2, 2]
assert_equal(out, tgt)

In [60]:
#check usage of out parameter of clip() and check that refer variable overrides value of arr1 and arr2
arr1 = np.array([-1, 5, 2, 3, 10, -4, -9])
arr2 = np.array([7, 3, 4, -3, 10, -6])
for refer in [arr1, arr2]:
    np.clip(refer, 2, 7, out=refer)
tgt = [2, 5, 2, 3, 7, 2, 2]
assert_equal(arr1, tgt)
tgt = [7, 3, 4, 2, 7, 2]
assert_equal(arr2, tgt)

### np.random.choice()

In [40]:
np.random.seed(0)
p = np.array([0.1, 0.0, 0.7, 0.2])
index = np.random.choice([0, 1, 2, 3], p = p.ravel())
print(index)

2


flatten always returns a copy.

ravel returns a view of the original array whenever possible. This isn't visible in the printed output, but if you modify the array returned by ravel, it may modify the entries in the original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be faster since no memory is copied, but you have to be more careful about modifying the array it returns.

reshape((-1,)) gets a view whenever the strides of the array allow it even if that means you don't always get a contiguous array.

## One Hot Encoding

In [4]:
nb_classes = 6
targets = np.array([[2, 3, 4, 0]]).reshape(-1)
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [5]:
def one_hot_basic(targets, classes):
    res = np.eye(classes)[np.array(targets).reshape(-1)]
    return res
    #return res.reshape(list(targets.shape)+[classes])

one_hot_basic(np.array([2, 3, 4, 0]), 6)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [ ]:
def one_hot(indices, classes):
    res = np.eye(classes)[np.array(targets).reshape(-1)]
    return res
    #return res.reshape(list(targets.shape)+[classes])

one_hot(np.array([2, 3, 4, 0]), 6)

In [7]:
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth) 

<tf.Tensor 'one_hot:0' shape=(3, 3) dtype=float32>